//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRappointmentsWebApplication.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(":80")]
        public string WebServicePort {
            get {
                return ((string)(this["WebServicePort"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.200")]
        public string WebServiceIP {
            get {
                return ((string)(this["WebServiceIP"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string WebServiceLocation {
            get {
                return ((string)(this["WebServiceLocation"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("WebServices/")]
        public string WebServiceDirectory {
            get {
                return ((string)(this["WebServiceDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string WebServiceSyncMode {
            get {
                return ((string)(this["WebServiceSyncMode"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.201:5555/WebServices/Appointments.asmx")]
        public string RRappointmentsWebApplication_AppointmentsWebReference_Appointments {
            get {
                return ((string)(this["RRappointmentsWebApplication_AppointmentsWebReference_Appointments"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string UseWcfDiariesCounterService {
            get {
                return ((string)(this["UseWcfDiariesCounterService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.200:5555/WebServices/UserLogin.asmx")]
        public string RRappointmentsWebApplication_UserLoginWebReference_UserLogin {
            get {
                return ((string)(this["RRappointmentsWebApplication_UserLoginWebReference_UserLogin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.200:5555/WebServices/PasswordRecovery.asmx")]
        public string RRappointmentsWebApplication_PasswordRecoveryWebReference_PasswordRecovery {
            get {
                return ((string)(this["RRappointmentsWebApplication_PasswordRecoveryWebReference_PasswordRecovery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.200:5555/WebServices/NewUserSignUp.asmx")]
        public string RRappointmentsWebApplication_NewUserSignUpWebReference_NewUserSignUp {
            get {
                return ((string)(this["RRappointmentsWebApplication_NewUserSignUpWebReference_NewUserSignUp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.200:5555/WebServices/TreatmentInstruction.asmx")]
        public string RRappointmentsWebApplication_TreatmentInstructionWebReference_TreatmentInstruction {
            get {
                return ((string)(this["RRappointmentsWebApplication_TreatmentInstructionWebReference_TreatmentInstructio" +
                    "n"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.200:5555/WebServices/NewAppointment.asmx")]
        public string RRappointmentsWebApplication_NewAppointmentWebReference_NewAppointment {
            get {
                return ((string)(this["RRappointmentsWebApplication_NewAppointmentWebReference_NewAppointment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.201:5555/WebServices/EmailSender.asmx")]
        public string RRappointmentsWebApplication_EmailSenderWebReference_EmailSender {
            get {
                return ((string)(this["RRappointmentsWebApplication_EmailSenderWebReference_EmailSender"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:2417/WebServices/PasswordRecovery.asmx")]
        public string RRappointmentsWebApplication_PasswordRecoveryLocalWebReference_PasswordRecovery {
            get {
                return ((string)(this["RRappointmentsWebApplication_PasswordRecoveryLocalWebReference_PasswordRecovery"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:2417/WebServices/NewUserSignUp.asmx")]
        public string RRappointmentsWebApplication_NewUserSignUpLocalWebReference_NewUserSignUp {
            get {
                return ((string)(this["RRappointmentsWebApplication_NewUserSignUpLocalWebReference_NewUserSignUp"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:2417/WebServices/Appointments.asmx")]
        public string RRappointmentsWebApplication_AppointmentsLocalWebReference_Appointments {
            get {
                return ((string)(this["RRappointmentsWebApplication_AppointmentsLocalWebReference_Appointments"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:2417/WebServices/TreatmentInstruction.asmx")]
        public string RRappointmentsWebApplication_TreatmentInstructionLocalWebReference_TreatmentInstruction {
            get {
                return ((string)(this["RRappointmentsWebApplication_TreatmentInstructionLocalWebReference_TreatmentInstr" +
                    "uction"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:2417/WebServices/UserLogin.asmx")]
        public string RRappointmentsWebApplication_UserLoginLocalWebReference_UserLogin {
            get {
                return ((string)(this["RRappointmentsWebApplication_UserLoginLocalWebReference_UserLogin"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:2417/WebServices/NewAppointment.asmx")]
        public string RRappointmentsWebApplication_NewAppointmentLocalWebReference_NewAppointment {
            get {
                return ((string)(this["RRappointmentsWebApplication_NewAppointmentLocalWebReference_NewAppointment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:2417/WebServices/EmailSender.asmx")]
        public string RRappointmentsWebApplication_EmailSenderLocalWebReference_EmailSender {
            get {
                return ((string)(this["RRappointmentsWebApplication_EmailSenderLocalWebReference_EmailSender"]));
            }
        }
    }
}
