//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RRappointmentsWebApplication.TreatmentInstructionWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TreatmentInstructionSoap", Namespace="http://tempuri.org/")]
    public partial class TreatmentInstruction : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTreatmentInstructionsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSiteInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TreatmentInstruction() {
            this.Url = global::RRappointmentsWebApplication.Properties.Settings.Default.RRappointmentsWebApplication_TreatmentInstructionWebReference_TreatmentInstruction;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTreatmentInstructionsCompletedEventHandler GetTreatmentInstructionsCompleted;
        
        /// <remarks/>
        public event GetSiteInfoCompletedEventHandler GetSiteInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTreatmentInstructions", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTreatmentInstructions(int jsonOperCode) {
            object[] results = this.Invoke("GetTreatmentInstructions", new object[] {
                        jsonOperCode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTreatmentInstructionsAsync(int jsonOperCode) {
            this.GetTreatmentInstructionsAsync(jsonOperCode, null);
        }
        
        /// <remarks/>
        public void GetTreatmentInstructionsAsync(int jsonOperCode, object userState) {
            if ((this.GetTreatmentInstructionsOperationCompleted == null)) {
                this.GetTreatmentInstructionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTreatmentInstructionsOperationCompleted);
            }
            this.InvokeAsync("GetTreatmentInstructions", new object[] {
                        jsonOperCode}, this.GetTreatmentInstructionsOperationCompleted, userState);
        }
        
        private void OnGetTreatmentInstructionsOperationCompleted(object arg) {
            if ((this.GetTreatmentInstructionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTreatmentInstructionsCompleted(this, new GetTreatmentInstructionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSiteInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SiteInfo GetSiteInfo(int jsonBranchCode) {
            object[] results = this.Invoke("GetSiteInfo", new object[] {
                        jsonBranchCode});
            return ((SiteInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetSiteInfoAsync(int jsonBranchCode) {
            this.GetSiteInfoAsync(jsonBranchCode, null);
        }
        
        /// <remarks/>
        public void GetSiteInfoAsync(int jsonBranchCode, object userState) {
            if ((this.GetSiteInfoOperationCompleted == null)) {
                this.GetSiteInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSiteInfoOperationCompleted);
            }
            this.InvokeAsync("GetSiteInfo", new object[] {
                        jsonBranchCode}, this.GetSiteInfoOperationCompleted, userState);
        }
        
        private void OnGetSiteInfoOperationCompleted(object arg) {
            if ((this.GetSiteInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSiteInfoCompleted(this, new GetSiteInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SiteInfo {
        
        private string siteNameField;
        
        private string addressField;
        
        private string isActiveField;
        
        private string phone1Field;
        
        private string phone2Field;
        
        private string mobileField;
        
        private string faxNumField;
        
        private string docNameField;
        
        private string emailField;
        
        /// <remarks/>
        public string SiteName {
            get {
                return this.siteNameField;
            }
            set {
                this.siteNameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
        
        /// <remarks/>
        public string Phone1 {
            get {
                return this.phone1Field;
            }
            set {
                this.phone1Field = value;
            }
        }
        
        /// <remarks/>
        public string Phone2 {
            get {
                return this.phone2Field;
            }
            set {
                this.phone2Field = value;
            }
        }
        
        /// <remarks/>
        public string Mobile {
            get {
                return this.mobileField;
            }
            set {
                this.mobileField = value;
            }
        }
        
        /// <remarks/>
        public string FaxNum {
            get {
                return this.faxNumField;
            }
            set {
                this.faxNumField = value;
            }
        }
        
        /// <remarks/>
        public string DocName {
            get {
                return this.docNameField;
            }
            set {
                this.docNameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetTreatmentInstructionsCompletedEventHandler(object sender, GetTreatmentInstructionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTreatmentInstructionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTreatmentInstructionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetSiteInfoCompletedEventHandler(object sender, GetSiteInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSiteInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSiteInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SiteInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SiteInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591