//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RRappointmentsWebApplication.NewAppointmentWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NewAppointmentSoap", Namespace="http://tempuri.org/")]
    public partial class NewAppointment : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AddNewAppointmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerCodeForRemoteDiariesReportsOperationCompleted;
        
        private System.Threading.SendOrPostCallback OnLockAppointmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback OnUnlockAppointmentOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NewAppointment() {
            this.Url = global::RRappointmentsWebApplication.Properties.Settings.Default.RRappointmentsWebApplication_NewAppointmentWebReference_NewAppointment;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AddNewAppointmentCompletedEventHandler AddNewAppointmentCompleted;
        
        /// <remarks/>
        public event GetCustomerCodeForRemoteDiariesReportsCompletedEventHandler GetCustomerCodeForRemoteDiariesReportsCompleted;
        
        /// <remarks/>
        public event OnLockAppointmentCompletedEventHandler OnLockAppointmentCompleted;
        
        /// <remarks/>
        public event OnUnlockAppointmentCompletedEventHandler OnUnlockAppointmentCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AddNewAppointment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AppointmentMailData AddNewAppointment(string jsonDate, int jsonCustCode, int jsonSiteCode, int jsonOperCode, int jsonInsrCode, int jsonDline) {
            object[] results = this.Invoke("AddNewAppointment", new object[] {
                        jsonDate,
                        jsonCustCode,
                        jsonSiteCode,
                        jsonOperCode,
                        jsonInsrCode,
                        jsonDline});
            return ((AppointmentMailData)(results[0]));
        }
        
        /// <remarks/>
        public void AddNewAppointmentAsync(string jsonDate, int jsonCustCode, int jsonSiteCode, int jsonOperCode, int jsonInsrCode, int jsonDline) {
            this.AddNewAppointmentAsync(jsonDate, jsonCustCode, jsonSiteCode, jsonOperCode, jsonInsrCode, jsonDline, null);
        }
        
        /// <remarks/>
        public void AddNewAppointmentAsync(string jsonDate, int jsonCustCode, int jsonSiteCode, int jsonOperCode, int jsonInsrCode, int jsonDline, object userState) {
            if ((this.AddNewAppointmentOperationCompleted == null)) {
                this.AddNewAppointmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddNewAppointmentOperationCompleted);
            }
            this.InvokeAsync("AddNewAppointment", new object[] {
                        jsonDate,
                        jsonCustCode,
                        jsonSiteCode,
                        jsonOperCode,
                        jsonInsrCode,
                        jsonDline}, this.AddNewAppointmentOperationCompleted, userState);
        }
        
        private void OnAddNewAppointmentOperationCompleted(object arg) {
            if ((this.AddNewAppointmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddNewAppointmentCompleted(this, new AddNewAppointmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCustomerCodeForRemoteDiariesReports", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetCustomerCodeForRemoteDiariesReports() {
            object[] results = this.Invoke("GetCustomerCodeForRemoteDiariesReports", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerCodeForRemoteDiariesReportsAsync() {
            this.GetCustomerCodeForRemoteDiariesReportsAsync(null);
        }
        
        /// <remarks/>
        public void GetCustomerCodeForRemoteDiariesReportsAsync(object userState) {
            if ((this.GetCustomerCodeForRemoteDiariesReportsOperationCompleted == null)) {
                this.GetCustomerCodeForRemoteDiariesReportsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerCodeForRemoteDiariesReportsOperationCompleted);
            }
            this.InvokeAsync("GetCustomerCodeForRemoteDiariesReports", new object[0], this.GetCustomerCodeForRemoteDiariesReportsOperationCompleted, userState);
        }
        
        private void OnGetCustomerCodeForRemoteDiariesReportsOperationCompleted(object arg) {
            if ((this.GetCustomerCodeForRemoteDiariesReportsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerCodeForRemoteDiariesReportsCompleted(this, new GetCustomerCodeForRemoteDiariesReportsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OnLockAppointment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OnLockAppointment(int jsonDline) {
            object[] results = this.Invoke("OnLockAppointment", new object[] {
                        jsonDline});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OnLockAppointmentAsync(int jsonDline) {
            this.OnLockAppointmentAsync(jsonDline, null);
        }
        
        /// <remarks/>
        public void OnLockAppointmentAsync(int jsonDline, object userState) {
            if ((this.OnLockAppointmentOperationCompleted == null)) {
                this.OnLockAppointmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOnLockAppointmentOperationCompleted);
            }
            this.InvokeAsync("OnLockAppointment", new object[] {
                        jsonDline}, this.OnLockAppointmentOperationCompleted, userState);
        }
        
        private void OnOnLockAppointmentOperationCompleted(object arg) {
            if ((this.OnLockAppointmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OnLockAppointmentCompleted(this, new OnLockAppointmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OnUnlockAppointment", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string OnUnlockAppointment(int jsonDline) {
            object[] results = this.Invoke("OnUnlockAppointment", new object[] {
                        jsonDline});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void OnUnlockAppointmentAsync(int jsonDline) {
            this.OnUnlockAppointmentAsync(jsonDline, null);
        }
        
        /// <remarks/>
        public void OnUnlockAppointmentAsync(int jsonDline, object userState) {
            if ((this.OnUnlockAppointmentOperationCompleted == null)) {
                this.OnUnlockAppointmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOnUnlockAppointmentOperationCompleted);
            }
            this.InvokeAsync("OnUnlockAppointment", new object[] {
                        jsonDline}, this.OnUnlockAppointmentOperationCompleted, userState);
        }
        
        private void OnOnUnlockAppointmentOperationCompleted(object arg) {
            if ((this.OnUnlockAppointmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OnUnlockAppointmentCompleted(this, new OnUnlockAppointmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AppointmentMailData {
        
        private string emailSubjectField;
        
        private string userEmailField;
        
        private string emailMessageField;
        
        private string senderEmailField;
        
        private string contentTypeField;
        
        /// <remarks/>
        public string EmailSubject {
            get {
                return this.emailSubjectField;
            }
            set {
                this.emailSubjectField = value;
            }
        }
        
        /// <remarks/>
        public string UserEmail {
            get {
                return this.userEmailField;
            }
            set {
                this.userEmailField = value;
            }
        }
        
        /// <remarks/>
        public string EmailMessage {
            get {
                return this.emailMessageField;
            }
            set {
                this.emailMessageField = value;
            }
        }
        
        /// <remarks/>
        public string SenderEmail {
            get {
                return this.senderEmailField;
            }
            set {
                this.senderEmailField = value;
            }
        }
        
        /// <remarks/>
        public string ContentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AddNewAppointmentCompletedEventHandler(object sender, AddNewAppointmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddNewAppointmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddNewAppointmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public AppointmentMailData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((AppointmentMailData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetCustomerCodeForRemoteDiariesReportsCompletedEventHandler(object sender, GetCustomerCodeForRemoteDiariesReportsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerCodeForRemoteDiariesReportsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerCodeForRemoteDiariesReportsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void OnLockAppointmentCompletedEventHandler(object sender, OnLockAppointmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OnLockAppointmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OnLockAppointmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void OnUnlockAppointmentCompletedEventHandler(object sender, OnUnlockAppointmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OnUnlockAppointmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OnUnlockAppointmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591