//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RRappointmentsWebApplication.WcfDiariesCounterService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfDiariesCounterService.IDiariesCounter")]
    public interface IDiariesCounter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiariesCounter/UpdateRemoteDiariesReports", ReplyAction="http://tempuri.org/IDiariesCounter/UpdateRemoteDiariesReportsResponse")]
        int UpdateRemoteDiariesReports(int custCode, string addData, string progType);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDiariesCounterChannel : RRappointmentsWebApplication.WcfDiariesCounterService.IDiariesCounter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiariesCounterClient : System.ServiceModel.ClientBase<RRappointmentsWebApplication.WcfDiariesCounterService.IDiariesCounter>, RRappointmentsWebApplication.WcfDiariesCounterService.IDiariesCounter {
        
        public DiariesCounterClient() {
        }
        
        public DiariesCounterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiariesCounterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiariesCounterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiariesCounterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int UpdateRemoteDiariesReports(int custCode, string addData, string progType) {
            return base.Channel.UpdateRemoteDiariesReports(custCode, addData, progType);
        }
    }
}
