//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RRappointmentsWebApplication.UserLoginLocalWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="UserLoginSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(KeyValuePairOfStringArrayList[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class UserLogin : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CheckUserLoginOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public UserLogin() {
            this.Url = global::RRappointmentsWebApplication.Properties.Settings.Default.RRappointmentsWebApplication_UserLoginLocalWebReference_UserLogin;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CheckUserLoginCompletedEventHandler CheckUserLoginCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CheckUserLogin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SessionInfo CheckUserLogin(string jsonPassword, string jsonUserId) {
            object[] results = this.Invoke("CheckUserLogin", new object[] {
                        jsonPassword,
                        jsonUserId});
            return ((SessionInfo)(results[0]));
        }
        
        /// <remarks/>
        public void CheckUserLoginAsync(string jsonPassword, string jsonUserId) {
            this.CheckUserLoginAsync(jsonPassword, jsonUserId, null);
        }
        
        /// <remarks/>
        public void CheckUserLoginAsync(string jsonPassword, string jsonUserId, object userState) {
            if ((this.CheckUserLoginOperationCompleted == null)) {
                this.CheckUserLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckUserLoginOperationCompleted);
            }
            this.InvokeAsync("CheckUserLogin", new object[] {
                        jsonPassword,
                        jsonUserId}, this.CheckUserLoginOperationCompleted, userState);
        }
        
        private void OnCheckUserLoginOperationCompleted(object arg) {
            if ((this.CheckUserLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckUserLoginCompleted(this, new CheckUserLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SessionInfo {
        
        private string fileNumField;
        
        private string userPasswordField;
        
        private string lastNameField;
        
        private string cust_numField;
        
        private string first_nameField;
        
        private string id_numField;
        
        private string loginStatusField;
        
        private System.DateTime validPasswordField;
        
        private AvailableAppointment[] availableAppointmentsField;
        
        private OldAppointment[] oldAppointmentsField;
        
        private KeyValuePairOfStringArrayList[] groupOperLinkListField;
        
        private bool operationDuplicatedField;
        
        private string warningField;
        
        private object[] groupMessageListField;
        
        /// <remarks/>
        public string FileNum {
            get {
                return this.fileNumField;
            }
            set {
                this.fileNumField = value;
            }
        }
        
        /// <remarks/>
        public string UserPassword {
            get {
                return this.userPasswordField;
            }
            set {
                this.userPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Cust_num {
            get {
                return this.cust_numField;
            }
            set {
                this.cust_numField = value;
            }
        }
        
        /// <remarks/>
        public string First_name {
            get {
                return this.first_nameField;
            }
            set {
                this.first_nameField = value;
            }
        }
        
        /// <remarks/>
        public string Id_num {
            get {
                return this.id_numField;
            }
            set {
                this.id_numField = value;
            }
        }
        
        /// <remarks/>
        public string LoginStatus {
            get {
                return this.loginStatusField;
            }
            set {
                this.loginStatusField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime ValidPassword {
            get {
                return this.validPasswordField;
            }
            set {
                this.validPasswordField = value;
            }
        }
        
        /// <remarks/>
        public AvailableAppointment[] AvailableAppointments {
            get {
                return this.availableAppointmentsField;
            }
            set {
                this.availableAppointmentsField = value;
            }
        }
        
        /// <remarks/>
        public OldAppointment[] OldAppointments {
            get {
                return this.oldAppointmentsField;
            }
            set {
                this.oldAppointmentsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public KeyValuePairOfStringArrayList[] GroupOperLinkList {
            get {
                return this.groupOperLinkListField;
            }
            set {
                this.groupOperLinkListField = value;
            }
        }
        
        /// <remarks/>
        public bool OperationDuplicated {
            get {
                return this.operationDuplicatedField;
            }
            set {
                this.operationDuplicatedField = value;
            }
        }
        
        /// <remarks/>
        public string Warning {
            get {
                return this.warningField;
            }
            set {
                this.warningField = value;
            }
        }
        
        /// <remarks/>
        public object[] GroupMessageList {
            get {
                return this.groupMessageListField;
            }
            set {
                this.groupMessageListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AvailableAppointment {
        
        private string diary_nameField;
        
        private string dtimeField;
        
        private string ddateField;
        
        private string diarynumField;
        
        private string dlineField;
        
        private string ddayField;
        
        /// <remarks/>
        public string Diary_name {
            get {
                return this.diary_nameField;
            }
            set {
                this.diary_nameField = value;
            }
        }
        
        /// <remarks/>
        public string Dtime {
            get {
                return this.dtimeField;
            }
            set {
                this.dtimeField = value;
            }
        }
        
        /// <remarks/>
        public string Ddate {
            get {
                return this.ddateField;
            }
            set {
                this.ddateField = value;
            }
        }
        
        /// <remarks/>
        public string Diarynum {
            get {
                return this.diarynumField;
            }
            set {
                this.diarynumField = value;
            }
        }
        
        /// <remarks/>
        public string Dline {
            get {
                return this.dlineField;
            }
            set {
                this.dlineField = value;
            }
        }
        
        /// <remarks/>
        public string Dday {
            get {
                return this.ddayField;
            }
            set {
                this.ddayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class KeyValuePairOfStringArrayList {
        
        private object[] valueField;
        
        /// <remarks/>
        public object[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OldAppointment {
        
        private string appointmentTimeField;
        
        private string appointmentDateField;
        
        private string appointmentLocationField;
        
        private string appointmentDayField;
        
        private string appointmentOperNameField;
        
        private string instructionField;
        
        private string lineCodeField;
        
        /// <remarks/>
        public string AppointmentTime {
            get {
                return this.appointmentTimeField;
            }
            set {
                this.appointmentTimeField = value;
            }
        }
        
        /// <remarks/>
        public string AppointmentDate {
            get {
                return this.appointmentDateField;
            }
            set {
                this.appointmentDateField = value;
            }
        }
        
        /// <remarks/>
        public string AppointmentLocation {
            get {
                return this.appointmentLocationField;
            }
            set {
                this.appointmentLocationField = value;
            }
        }
        
        /// <remarks/>
        public string AppointmentDay {
            get {
                return this.appointmentDayField;
            }
            set {
                this.appointmentDayField = value;
            }
        }
        
        /// <remarks/>
        public string AppointmentOperName {
            get {
                return this.appointmentOperNameField;
            }
            set {
                this.appointmentOperNameField = value;
            }
        }
        
        /// <remarks/>
        public string Instruction {
            get {
                return this.instructionField;
            }
            set {
                this.instructionField = value;
            }
        }
        
        /// <remarks/>
        public string LineCode {
            get {
                return this.lineCodeField;
            }
            set {
                this.lineCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CheckUserLoginCompletedEventHandler(object sender, CheckUserLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckUserLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckUserLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SessionInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SessionInfo)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591