//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RRappointmentsWebApplication.PasswordRecoveryLocalWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PasswordRecoverySoap", Namespace="http://tempuri.org/")]
    public partial class PasswordRecovery : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback OnRecoverUserPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback OnUpdateUserPasswordOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNewUserPasswordDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PasswordRecovery() {
            this.Url = global::RRappointmentsWebApplication.Properties.Settings.Default.RRappointmentsWebApplication_PasswordRecoveryLocalWebReference_PasswordRecovery;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event OnRecoverUserPasswordCompletedEventHandler OnRecoverUserPasswordCompleted;
        
        /// <remarks/>
        public event OnUpdateUserPasswordCompletedEventHandler OnUpdateUserPasswordCompleted;
        
        /// <remarks/>
        public event GetNewUserPasswordDataCompletedEventHandler GetNewUserPasswordDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OnRecoverUserPassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserPasswordRecoveryData OnRecoverUserPassword(string jsonUserID) {
            object[] results = this.Invoke("OnRecoverUserPassword", new object[] {
                        jsonUserID});
            return ((UserPasswordRecoveryData)(results[0]));
        }
        
        /// <remarks/>
        public void OnRecoverUserPasswordAsync(string jsonUserID) {
            this.OnRecoverUserPasswordAsync(jsonUserID, null);
        }
        
        /// <remarks/>
        public void OnRecoverUserPasswordAsync(string jsonUserID, object userState) {
            if ((this.OnRecoverUserPasswordOperationCompleted == null)) {
                this.OnRecoverUserPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOnRecoverUserPasswordOperationCompleted);
            }
            this.InvokeAsync("OnRecoverUserPassword", new object[] {
                        jsonUserID}, this.OnRecoverUserPasswordOperationCompleted, userState);
        }
        
        private void OnOnRecoverUserPasswordOperationCompleted(object arg) {
            if ((this.OnRecoverUserPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OnRecoverUserPasswordCompleted(this, new OnRecoverUserPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/OnUpdateUserPassword", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool OnUpdateUserPassword(string jsonUserID) {
            object[] results = this.Invoke("OnUpdateUserPassword", new object[] {
                        jsonUserID});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void OnUpdateUserPasswordAsync(string jsonUserID) {
            this.OnUpdateUserPasswordAsync(jsonUserID, null);
        }
        
        /// <remarks/>
        public void OnUpdateUserPasswordAsync(string jsonUserID, object userState) {
            if ((this.OnUpdateUserPasswordOperationCompleted == null)) {
                this.OnUpdateUserPasswordOperationCompleted = new System.Threading.SendOrPostCallback(this.OnOnUpdateUserPasswordOperationCompleted);
            }
            this.InvokeAsync("OnUpdateUserPassword", new object[] {
                        jsonUserID}, this.OnUpdateUserPasswordOperationCompleted, userState);
        }
        
        private void OnOnUpdateUserPasswordOperationCompleted(object arg) {
            if ((this.OnUpdateUserPasswordCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.OnUpdateUserPasswordCompleted(this, new OnUpdateUserPasswordCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetNewUserPasswordData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public UserPasswordRecoveryData GetNewUserPasswordData(string jsonUserID, string jsonEmail, string jsonPhone, string jsonAreaCode, string jsonPassword) {
            object[] results = this.Invoke("GetNewUserPasswordData", new object[] {
                        jsonUserID,
                        jsonEmail,
                        jsonPhone,
                        jsonAreaCode,
                        jsonPassword});
            return ((UserPasswordRecoveryData)(results[0]));
        }
        
        /// <remarks/>
        public void GetNewUserPasswordDataAsync(string jsonUserID, string jsonEmail, string jsonPhone, string jsonAreaCode, string jsonPassword) {
            this.GetNewUserPasswordDataAsync(jsonUserID, jsonEmail, jsonPhone, jsonAreaCode, jsonPassword, null);
        }
        
        /// <remarks/>
        public void GetNewUserPasswordDataAsync(string jsonUserID, string jsonEmail, string jsonPhone, string jsonAreaCode, string jsonPassword, object userState) {
            if ((this.GetNewUserPasswordDataOperationCompleted == null)) {
                this.GetNewUserPasswordDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewUserPasswordDataOperationCompleted);
            }
            this.InvokeAsync("GetNewUserPasswordData", new object[] {
                        jsonUserID,
                        jsonEmail,
                        jsonPhone,
                        jsonAreaCode,
                        jsonPassword}, this.GetNewUserPasswordDataOperationCompleted, userState);
        }
        
        private void OnGetNewUserPasswordDataOperationCompleted(object arg) {
            if ((this.GetNewUserPasswordDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewUserPasswordDataCompleted(this, new GetNewUserPasswordDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserPasswordRecoveryData {
        
        private string clientCellNumberField;
        
        private string clientEmailField;
        
        private string clientPasswordField;
        
        private string senderEmailTitleField;
        
        private string recoveryMsgSMSField;
        
        private string recoveryMsgEmailField;
        
        private string senderCellNumberField;
        
        private string senderNameField;
        
        private string senderPasswordField;
        
        private string senderEmailField;
        
        private string contentTypeField;
        
        private string senderUrlField;
        
        /// <remarks/>
        public string ClientCellNumber {
            get {
                return this.clientCellNumberField;
            }
            set {
                this.clientCellNumberField = value;
            }
        }
        
        /// <remarks/>
        public string ClientEmail {
            get {
                return this.clientEmailField;
            }
            set {
                this.clientEmailField = value;
            }
        }
        
        /// <remarks/>
        public string ClientPassword {
            get {
                return this.clientPasswordField;
            }
            set {
                this.clientPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string SenderEmailTitle {
            get {
                return this.senderEmailTitleField;
            }
            set {
                this.senderEmailTitleField = value;
            }
        }
        
        /// <remarks/>
        public string RecoveryMsgSMS {
            get {
                return this.recoveryMsgSMSField;
            }
            set {
                this.recoveryMsgSMSField = value;
            }
        }
        
        /// <remarks/>
        public string RecoveryMsgEmail {
            get {
                return this.recoveryMsgEmailField;
            }
            set {
                this.recoveryMsgEmailField = value;
            }
        }
        
        /// <remarks/>
        public string SenderCellNumber {
            get {
                return this.senderCellNumberField;
            }
            set {
                this.senderCellNumberField = value;
            }
        }
        
        /// <remarks/>
        public string SenderName {
            get {
                return this.senderNameField;
            }
            set {
                this.senderNameField = value;
            }
        }
        
        /// <remarks/>
        public string SenderPassword {
            get {
                return this.senderPasswordField;
            }
            set {
                this.senderPasswordField = value;
            }
        }
        
        /// <remarks/>
        public string SenderEmail {
            get {
                return this.senderEmailField;
            }
            set {
                this.senderEmailField = value;
            }
        }
        
        /// <remarks/>
        public string ContentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        public string SenderUrl {
            get {
                return this.senderUrlField;
            }
            set {
                this.senderUrlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void OnRecoverUserPasswordCompletedEventHandler(object sender, OnRecoverUserPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OnRecoverUserPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OnRecoverUserPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserPasswordRecoveryData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserPasswordRecoveryData)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void OnUpdateUserPasswordCompletedEventHandler(object sender, OnUpdateUserPasswordCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OnUpdateUserPasswordCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal OnUpdateUserPasswordCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetNewUserPasswordDataCompletedEventHandler(object sender, GetNewUserPasswordDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNewUserPasswordDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNewUserPasswordDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public UserPasswordRecoveryData Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((UserPasswordRecoveryData)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591