//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RRappointmentsWebApplication.NewUserSignUpLocalWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="NewUserSignUpSoap", Namespace="http://tempuri.org/")]
    public partial class NewUserSignUp : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SignUpNewUserPerObjectOperationCompleted;
        
        private System.Threading.SendOrPostCallback SignUpNewUserPerParamsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public NewUserSignUp() {
            this.Url = global::RRappointmentsWebApplication.Properties.Settings.Default.RRappointmentsWebApplication_NewUserSignUpLocalWebReference_NewUserSignUp;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SignUpNewUserPerObjectCompletedEventHandler SignUpNewUserPerObjectCompleted;
        
        /// <remarks/>
        public event SignUpNewUserPerParamsCompletedEventHandler SignUpNewUserPerParamsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SignUpNewUserPerObject", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SignUpNewUserPerObject(UserInfo jsonUserInfo) {
            object[] results = this.Invoke("SignUpNewUserPerObject", new object[] {
                        jsonUserInfo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SignUpNewUserPerObjectAsync(UserInfo jsonUserInfo) {
            this.SignUpNewUserPerObjectAsync(jsonUserInfo, null);
        }
        
        /// <remarks/>
        public void SignUpNewUserPerObjectAsync(UserInfo jsonUserInfo, object userState) {
            if ((this.SignUpNewUserPerObjectOperationCompleted == null)) {
                this.SignUpNewUserPerObjectOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSignUpNewUserPerObjectOperationCompleted);
            }
            this.InvokeAsync("SignUpNewUserPerObject", new object[] {
                        jsonUserInfo}, this.SignUpNewUserPerObjectOperationCompleted, userState);
        }
        
        private void OnSignUpNewUserPerObjectOperationCompleted(object arg) {
            if ((this.SignUpNewUserPerObjectCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SignUpNewUserPerObjectCompleted(this, new SignUpNewUserPerObjectCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SignUpNewUserPerParams", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SignUpNewUserPerParams(string jsonId, string jsonFirstName, string jsonLastName, string jsonEmail, string jsonAreaCode, string jsonPhoneNumber, string jsonPassword) {
            object[] results = this.Invoke("SignUpNewUserPerParams", new object[] {
                        jsonId,
                        jsonFirstName,
                        jsonLastName,
                        jsonEmail,
                        jsonAreaCode,
                        jsonPhoneNumber,
                        jsonPassword});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SignUpNewUserPerParamsAsync(string jsonId, string jsonFirstName, string jsonLastName, string jsonEmail, string jsonAreaCode, string jsonPhoneNumber, string jsonPassword) {
            this.SignUpNewUserPerParamsAsync(jsonId, jsonFirstName, jsonLastName, jsonEmail, jsonAreaCode, jsonPhoneNumber, jsonPassword, null);
        }
        
        /// <remarks/>
        public void SignUpNewUserPerParamsAsync(string jsonId, string jsonFirstName, string jsonLastName, string jsonEmail, string jsonAreaCode, string jsonPhoneNumber, string jsonPassword, object userState) {
            if ((this.SignUpNewUserPerParamsOperationCompleted == null)) {
                this.SignUpNewUserPerParamsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSignUpNewUserPerParamsOperationCompleted);
            }
            this.InvokeAsync("SignUpNewUserPerParams", new object[] {
                        jsonId,
                        jsonFirstName,
                        jsonLastName,
                        jsonEmail,
                        jsonAreaCode,
                        jsonPhoneNumber,
                        jsonPassword}, this.SignUpNewUserPerParamsOperationCompleted, userState);
        }
        
        private void OnSignUpNewUserPerParamsOperationCompleted(object arg) {
            if ((this.SignUpNewUserPerParamsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SignUpNewUserPerParamsCompleted(this, new SignUpNewUserPerParamsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class UserInfo {
        
        private string passwordField;
        
        private string phoneNumberField;
        
        private string areaCodeField;
        
        private string lastNameField;
        
        private string emailField;
        
        private string first_nameField;
        
        private string id_numField;
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string AreaCode {
            get {
                return this.areaCodeField;
            }
            set {
                this.areaCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string First_name {
            get {
                return this.first_nameField;
            }
            set {
                this.first_nameField = value;
            }
        }
        
        /// <remarks/>
        public string Id_num {
            get {
                return this.id_numField;
            }
            set {
                this.id_numField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SignUpNewUserPerObjectCompletedEventHandler(object sender, SignUpNewUserPerObjectCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SignUpNewUserPerObjectCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SignUpNewUserPerObjectCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SignUpNewUserPerParamsCompletedEventHandler(object sender, SignUpNewUserPerParamsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SignUpNewUserPerParamsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SignUpNewUserPerParamsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591